/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package group_project;

import static group_project.Group_Project.discount;
import static group_project.Group_Project.extraChairs;
import static group_project.Group_Project.initialPrice;
import static group_project.Group_Project.numPeople;
import static group_project.Group_Project.numTables;
import static group_project.Group_Project.priceTotal;
import static group_project.Group_Project.taxValue;
import static group_project.Group_Project.totalChairs;
import java.io.FileWriter;
import java.io.IOException;
import java.text.NumberFormat;


/**
 *
 * @author mclaughc1461
 */
public class Project_SaveInvoice_JForm
        extends javax.swing.JFrame
{

    /**
     * Creates new form Project_JForm
     */
    public Project_SaveInvoice_JForm()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        SI_FileChooser = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);

        SI_FileChooser.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        SI_FileChooser.setApproveButtonText("Save");
        SI_FileChooser.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                SI_FileChooserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SI_FileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(SI_FileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void SI_FileChooserActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_SI_FileChooserActionPerformed
    {//GEN-HEADEREND:event_SI_FileChooserActionPerformed
        NumberFormat formatter = NumberFormat.getCurrencyInstance();
       
        try(FileWriter fWriter = new FileWriter (SI_FileChooser.getSelectedFile()+".txt"))
        {
            fWriter.write("Humu Table Services" + "\n" + "_________________" + "\n" + "\n");
            fWriter.write("Number of people in your group: " + numPeople + "\n" 
                    + "Number of tables: " + numTables + "\n" 
                    + "Number of chairs: " + totalChairs + "\n"
                    + "Number of extra chairs: " + extraChairs + "\n" + "\n"
                    + "_________________" + "\n"
                    + "Subtotal: " + formatter.format(initialPrice)+ "\n"
                    + "Tax: " + formatter.format(taxValue) + "\n" 
                    + "Discount: " + formatter.format(discount) + "\n"
                    + "Total: " + formatter.format(priceTotal) + "\n");
        }
        
        catch (IOException e)
        {
            System.out.println("An error has occurred.");
            System.out.print(e);
        }
        
        this.dispose();
    }//GEN-LAST:event_SI_FileChooserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info
                    : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        }
        catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Project_SaveInvoice_JForm.class.getName()).
                    log(java.util.logging.Level.SEVERE,
                            null,
                            ex);
        }
        catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Project_SaveInvoice_JForm.class.getName()).
                    log(java.util.logging.Level.SEVERE,
                            null,
                            ex);
        }
        catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Project_SaveInvoice_JForm.class.getName()).
                    log(java.util.logging.Level.SEVERE,
                            null,
                            ex);
        }
        catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Project_SaveInvoice_JForm.class.getName()).
                    log(java.util.logging.Level.SEVERE,
                            null,
                            ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Project_SaveInvoice_JForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser SI_FileChooser;
    // End of variables declaration//GEN-END:variables
}
